# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype2', models.CharField(choices=[('1', '\u666e\u901a\u7528\u6237'), ('2', '\u7ba1\u7406\u7528\u6237'), ('3', '\u8d85\u7ea7\u7ba1\u7406\u5458')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('group_relation', models.ManyToManyField(to='web.Group')),
            ],
        ),
        migrations.CreateModel(
            name='usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Createdate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='CreateDate',
            field=models.DateTimeField(default='20171118'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(default='18'),
        ),
    ]
