# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171124_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='CreateDate',
            field=models.DateTimeField(default='2017-11-18 00:22:22'),
        ),
    ]
